### ISSUE TITLE
Quasi-quoter to statically verify all template variables are present

### ISSUE THREAD

**Issue by roosemberth** [tfausak/burrito#15]
It would be nice if I could check at compile-time that all the variables in a template are present.
The current `render` implementation replaces unexisting patterns with empty values, which may not always be desirable, in particular when dealing with `:{password}` or `:{port}` elements (since there's no expansion to prepending `:` and the result may be a malformed URI).

**Comment by tfausak** [comment]
I think that Burrito exposes enough stuff to implement this currently. In particular the [`expandWith`](https://hackage.haskell.org/package/burrito-1.2.0.2/docs/Burrito.html#v:expandWith) function lets you operate in any `Monad`. So for example here's expansion in `Either String Builder`:

``` hs
>>> parse "127.0.0.1:{port}"
Just 127.0.0.1:{port}
>>> expandWith (\ x -> Left $ "not found: " <> show x) template
Left "not found: \"port\""
```

That could be used as the basis for a Template Haskell function that renders a template while making sure that all variables are present. I'd be happy to provide such a function, but it might take me a little bit to write.

**Comment by tfausak** [comment]
Does this work for you? 

``` hs
import qualified Burrito
import qualified Data.Bifunctor as Bifunctor
import qualified Data.Map as Map
import qualified Data.Text as Text
import qualified Data.Text.Lazy as LazyText
import qualified Data.Text.Lazy.Builder as Builder

parse :: MonadFail m => String -> m Burrito.Template
parse = maybe (fail "invalid template") pure . Burrito.parse

expand :: MonadFail m => [(String, Burrito.Value)] -> Burrito.Template -> m String
expand xs = let
  m = Map.fromList $ fmap (Bifunctor.first Text.pack) xs
  f k = maybe (Left $ "missing variable: " <> show k) (Right . Just) $ Map.lookup k m
  in either fail (pure . LazyText.unpack . Builder.toLazyText) . Burrito.expandWith f
```

``` hs
-- example usage

ghci> do { t <- parse "{host}"; expand [] t }
*** Exception: user error (missing variable: "host")

ghci> do { t <- parse "{host}"; expand [("host", Burrito.stringValue "localhost")] t }
"localhost"
```

**Comment by tfausak** [comment]
After thinking about this for a while, I'm curious about your use case. In which scenario are you using Burrito where both the URI template and the variables are known at compile time? Is it possible that something like [PyF](https://hackage.haskell.org/package/PyF) could provide a better experience?

**Comment by roosemberth** [comment]
Sorry for my lack of response, I haven't had the time to test your provided solutions. The is the code snippet where I'm using uriTemplate:

```haskell
    convert DatabaseConfig{..} = DbConnectionStr . encodeUtf8 . toS $ expand
      [ ("username", stringValue $ toS username)
      , ("password", stringValue $ toS password)
      , ("host", stringValue $ toS host)
      , ("port", stringValue $ show port)
      , ("name", stringValue $ toS name)
      ] [uriTemplate|postgresql://{username}:{password}@{host}:{port}/{name}|]
```

**Comment by roosemberth** [comment]
I don't think PyF would be a better solution. I specifically use the library to avoid manual URL escaping.

**Comment by tfausak** [comment]
It turns out that supporting this is a little trickier than I anticipated. Doing the actual parsing and expanding is relatively straightforward; I provided that in an earlier comment. Since that works with any `MonadFail`, it can be used in a Template Haskell splice. From there it's a small step to do everything in one go, which allows expressions like `$( parseAndExpand "{issue}" [("issue", stringValue "15")] )`. That's perhaps an improvement, but it's not very satisfying. 

Ideally I could provide a quasi-quoter that parses the template, then expands it using whichever values are in scope. This is where things get tricky. Burrito doesn't currently have an intermediate representation. It goes straight from a template to a text builder. This is relevant because the typical way to evaluate a formatted string is to turn things like `[qq|foo${bar}|]` into `("foo" ++ bar)`, more or less. 

So what this feature demands is a step in the middle that emits a bunch of builds squished together, like `builder "foo" <> builder bar`. I could maybe do that currently with `value` and `literal` from `Burrito.Internal.Expand`, but then I'd have to re-implement the token traversal.
